### ISSUE TITLE
Progress bar not working on some routes

### ISSUE THREAD

**Issue by FrciSmrci** [MurhafSousli/ngx-progressbar#189]
Hi @MurhafSousli 

I looked through the open and closed issues and didn't find anything similar.

I'm using Angular 6 and `"@ngx-progressbar/core": "5.0.1", "@ngx-progressbar/router": "5.0.1",` version.

Issue: The progress bar works smoothly on some pages, while it doesn't show up on others. I tried to find a differentiator in both examples, but had no success. 

Do you have any idea why this may occur? 

Thank you in advance.

Have an awesome day! :)

**Comment by MurhafSousli** [comment]
Hi @FrciSmrci 

I am aware of this, since I added the `[debounceTime]` option in version [4.3.0](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md#430), the progress bar doesn't start if the `complete()` is called immediately after `start()` (we are talking about fractions of a second) which is the cause in your routes events.

I use this feature in 2 web apps, [here](https://murhafsousli.github.io/ngx-sharebuttons/) and [here](https://murhafsousli.github.io/ngx-gallery/)
The first time you navigate you will see the progress bar but the second time, it does not because it was already loaded which actually makes sense!

I recommend you to use the lazy routes whenever you can (if you're not already using them) so the routes do an actual request, but note that if the lazy route was already visited then the progress bar might not start for the same reason.

**Comment by FrciSmrci** [comment]
@MurhafSousli Thanks for the quick response. 

I do use lazy routes, but not for every route. The debounceTime option does make sense.

I'm going to close the issue, have a great day! :)

**Comment by MurhafSousli** [comment]
@FrciSmrci Thanks, you are welcome!
