### ISSUE TITLE
The pipe 'async' could not be found

### ISSUE THREAD

**Issue by qaxqaxqax** [MurhafSousli/ngx-progressbar#242]
### Bug Report
```
- [x] bug report 
- [ ] feature request
- [ ] question
```

### Versions
Output from: Angular 7

### Repro steps

- Generate new project
- Add progressbar
- ng build --prod --build-optimizer --project=projectname

### The log given by the failure
```
ERROR in : Template parse errors:
The pipe 'async' could not be found ("
    <ng-container [ERROR ->]*ngIf="state$ | async; let state">
      <div class="ng-progress-bar"
            [class.-active]="st"): ...path/node_modules/@ngx-progressbar/core/ngx-progressbar-core.d.ts.NgProgressComponent.html@1:18
```

### Desired functionality
prod build without error

**Comment by MurhafSousli** [comment]
This is unclear!! what are you trying to accomplish? and which version are you using?

Guessing trying to integrate it with custom progress bar!

Since [5.2.0](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md#520) it became `progressRef.state` not `progressRef.state$`, see [integration example](https://github.com/MurhafSousli/ngx-progressbar/wiki/Integration)
