### ISSUE TITLE
v6.0.2 does not work with Angular 8

### ISSUE THREAD

**Issue by cyberbobjr** [MurhafSousli/ngx-progressbar#274]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-progressbar

Steps to reproduce:
1. Install ngx-progressbar@6.0.2
2. build your projet
 
#### Expected Behavior
no error

#### Actual Behavior
An error when building my project :

```
ERROR in node_modules/ngx-progressbar/lib/ng-progress-ref.d.ts:15:17 - error TS1086: An accessor cannot be declared in an ambient context.

15     private get currState();
                   ~~~~~~~~~
node_modules/ngx-progressbar/lib/ng-progress-ref.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.

16     get isStarted(): boolean;
           ~~~~~~~~~
node_modules/ngx-progressbar/lib/ng-progress.component.d.ts:35:9 - error TS1086: An accessor cannot be declared in an ambient context.

35     get isStarted(): boolean;
           ~~~~~~~~~
```

#### Environment

- Angular: 
````
"@angular/animations": "^8.2.14",
        "@angular/cdk": "^8.2.3",
        "@angular/common": "^8.2.14",
        "@angular/compiler": "^8.2.14",
        "@angular/core": "^8.2.14",
        "@angular/forms": "^8.2.14",
        "@angular/platform-browser": "^8.2.14",
        "@angular/platform-browser-dynamic": "^8.2.14",
        "@angular/router": "^8.2.14",
````
- ngx-progressbar: "ngx-progressbar": "^6.0.2",

- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Catalina

**Comment by MurhafSousli** [comment]
Did you try v6.0.1?

**Comment by cyberbobjr** [comment]
6.0.1 it’s ok

**Comment by MurhafSousli** [comment]
I did not try 6.0.2 with Angular 8! but it expects it to work because the code did not change.

v6.0.1 is same as v6.0.2, the only changes are removing the warning when the package is installed in Angular 9 app and upgrade the build setup to Angular 9

https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md#602

**Comment by skermajo** [comment]
Having the same issue. 6.0.1 is ok, 6.0.2 fails with the same error.

**Comment by cm0s** [comment]
Same problem

**Comment by superjulius** [comment]
@MurhafSousli The issue is caused by the change of Typescript version.

In 6.0.1, the TS version is 3.5.3 while it is 3.7.5 with the upgrade for Angular 9 https://github.com/MurhafSousli/ngx-progressbar/issues/274#issuecomment-593001155

I suspect that upgrading TS to 3.7.5 with Angular 8 should work; however it is not supported so maybe better to stay on 6.0.1 for Angular 8.x users until they upgrade to 9
