### ISSUE TITLE
ObjectUnsubscribedError

### ISSUE THREAD

**Issue by noob9527** [MurhafSousli/ngx-progressbar#81]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

**Minimal usage of the plugin**
1. create project
```bash
ng new whatever
```
2. create two component
```bash
ng generate header
ng generate without-header
```
```javascript
// header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  template: `
    <ng-progress></ng-progress>
    <p>
      header Works!
    </p>
  `,
  styles: []
})
export class HeaderComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```
```javascript
//without-header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-without-header',
  template: `
   <p>
  		without-header Works!
   </p>
  `,
  styles: []
})
export class WithoutHeaderComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }
}
```
3. update AppModule
```javascript
//app.module.ts
import { RouterModule, Routes } from '@angular/router';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { NgProgressModule } from 'ngx-progressbar';

import { AppComponent } from './app.component';
import { HeaderComponent } from './header/header.component';
import { WithoutHeaderComponent } from './without-header/without-header.component';

const routes: Routes = [
  { path: '', redirectTo: 'withHeader', pathMatch: 'full' },
  { path: 'withHeader', component: HeaderComponent },
  { path: 'withoutHeader', component: WithoutHeaderComponent },
];

@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    WithoutHeaderComponent,
  ],
  imports: [
    BrowserModule,
    NgProgressModule,
    RouterModule.forRoot(routes),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
```html
<!-- app.component.html -->
<ul>
  <li>
    <h2><a [routerLink]="['withHeader']">withHeader</a></h2>
  </li>
  <li>
    <h2><a [routerLink]="['withoutHeader']">withoutHeader</a></h2>
  </li>
</ul>
<router-outlet></router-outlet>
```
4. click withoutHeader link then click withHeader link. error occurs
```
ProgressComponent.html:2 ERROR 
ObjectUnsubscribedError 
message : "object unsubscribed"
name : "ObjectUnsubscribedError"
```

[this error may be related to these two lines](https://github.com/MurhafSousli/ngx-progressbar/blob/master/src/components/progress.component.ts#L99-L100)

**Comment by MurhafSousli** [comment]
Hi @noob9527 `<ng-progress>` should be placed in a component that does not get destroyed.
Ideally it should be place in your root component `app.component.ts`
dup #41

**Comment by PowerKiKi** [comment]
Like a few others before me I also stumbled upon this issue. And I must agree with @noob9527 that the problem is with the  `ngOnDestroy()`. In my tests removing this method, fixed the crash. What is even the point of having that method if the component must never be destroyed ? Shouldn't it be removed altogether ?

To have this restriction that `<ng-progress>` must never be destroyed, means to force the same layout for the entire application. That is a pretty strong limitation that have a very visible effect for end-user.

In my case I have a very simple login page with a very minimal design where I do not want `<ng-progress>`. Then in most pages for the rest of the app, I will have `<ng-progress>` within one of my component (visually bellow the top horizontal navbar). But that means that the app will crash whenever a user goes back to the login page. It's really not ideal.

Would you accept a PR to remove `ngOnDestroy()` ?

**Comment by MurhafSousli** [comment]
@PowerKiKi I just reviewed the code again, it makes sense.
There is no need to unsubscribe on component destroy.
Yes give me a PR, Thanks
